### ISSUE TITLE
从ubuntu官方源删除此源

### ISSUE THREAD

**Issue by RobberPhex** [nwafu-mta/nwafu-mirrors-help#1]
根据<https://www.v2ex.com/t/598436>和<https://nwafu-mirrors-help.readthedocs.io/>，这个源并不是对外使用的，所以建议从[官方源列表](http://mirrors.ubuntu.com/CN.txt)删除

**Comment by bianyifan** [comment]
限速目前已被提高，未来有计划对公网不限速服务。

在 2019年9月6日，18:19，Robert LU <notifications@github.com<mailto:notifications@github.com>> 写道：


根据https://www.v2ex.com/t/598436和https://nwafu-mirrors-help.readthedocs.io/，这个源并不是对外使用的，所以建议从官方源列表<http://mirrors.ubuntu.com/CN.txt>删除

**Comment by bianyifan** [comment]
致所有公网用户：

在2015年前后本站建立时，仅有CentOS镜像，受CentOS官方限制，此镜像需要对公网可见。但是进入官方源列表后，大量来自公网的请求导致学校教育网出口被占用，不能正常提供其他服务。当时采取了对所有用户限速10k的策略，而且CentOS是默认启用 fastestmirror 的……

2018年，镜像站开始提供更多服务，也一直试图平衡校外用户使用需求和出口容量有限的问题。因此限速被适当提高。根据统计情况来看，可以适当提高限速。因此我们在前些时间将限速提升至每连接 400KB/s 。我们会与学校网络中心沟通，将镜像站服务放在另一带宽资源丰富的出口对外提供不限速服务。

**Comment by kinosang** [comment]
如果带宽资源不是那么充足，建议还是主动申请从官方源移除比较好

毕竟很多时候自动化批量部署不方便手动换源，那么就有极大几率随机到此源，给 ops 造成很大困扰

* 请键盘侠不要怒喷“贡献即真理”，我做过长达七年多开源镜像站的维护工作，也知道要付出多少人力物力，但是因为我参与的站不能稳定对外提供服务所以从来没申请过官方列表

**Comment by bianyifan** [comment]
> 如果带宽资源不是那么充足，建议还是主动申请从官方源移除比较好

那采纳您的建议，Ubuntu源暂时限制校外访问，Ubuntu官方的检测机制会自动将此源在列表中隐藏。但是我并不清楚安装程序会如何选择源。

> 毕竟很多时候自动化批量部署不方便手动换源，那么就有极大几率随机到此源，给 ops 造成很大困扰

这点不敢苟同。在 Preseed 文件中可以手动设置源：

```
d-i mirror/country string manual
d-i mirror/http/hostname string mirrors.nwafu.edu.cn
d-i mirror/http/directory string /ubuntu
d-i mirror/http/proxy string
```

**Comment by hye** [comment]
> 手动设置源

手动设置源不应该是贵校师生自己 **手工设置**你们**专有的**服务器么， 为什么要绑架所有CN用户？

**Comment by hye** [comment]
举个不甚恰当的例子，贵校自己修了一条从机场到学校的“高速公路”， 但gf要求公开大家都能用，于是贵校逼不得已开放了，但要求非贵校人员需开车以步行速度通过“高速公路”。

面对被导航到这条公路的全国人民：
你完全可以自己从导航里删除这条“高速公路”啊

**Comment by LokiSharp** [comment]
我不是很能理解为什么你们要强迫公共用户手动设置源，国家镜像源列表本来就是为了方便特定地区的用户自动配置而设立的。事实上手动配置镜像源通常情况下只有在自己建立私有源或网络条件十分恶劣时才会进行。

关于镜像源的部署要求请阅读镜像源部署指南，请保证镜像可用性以及做好应对大量流量的准备。

> Be committed to being a mirror. Obviously, each offer to be an Ubuntu mirror is great and users appreciate it. However, it's in nobody's interest to go and change the sources.list every time a mirror disappears. So if you're not planning on creating a mirror for the long run, don't register it. People might get disappointed in you and/or Ubuntu.
> Know what you're starting with. A mirror may cause a lot of traffic. If your server has insufficient bandwidth, users cannot download very well and your machine may become unreachable. If you pay for traffic, please note that traffic might increase, a lot.

Ref: https://wiki.ubuntu.com/Mirrors

**Comment by hye** [comment]
英文好的翻译给官方看一下维护方的声明/解释？
Ref: https://ubuntuforums.org/showthread.php?t=2426252

**Comment by bianyifan** [comment]
我们已经把此镜像从 Ubuntu 官方镜像列表中撤掉。

**Comment by TurnOffNOD** [comment]
@bianyifan 说句实在话，这次争议最最主要的原因就是你们做错了一件事，而更扎你们心的是你们也只做错了这一件事：对外每个连接限速40kBps却仍然留在了官方源列表当中。

限速40kBps本身这件事并没有什么做错的地方；而进入官方源列表当中还限速，只要限速不是过分的话（比如说你们后来修改到的400kBps这个数值）也没有任何做错的地方。但是二者结合在一起：既限速40kBps这么过分又要留在官方源列表里，这就是自己找骂了。

可能你们也委屈：客观因素是你们那里学校的对外带宽太窄了，而主观因素是你们老师和领导们又给予了压力，你们不得不限速40kBps啊。那么就可以看看前辈们是怎么做的吧：10年前在公网上有两个大公司支持的开源镜像，就是163镜像（mirrors.163）和搜狐镜像（mirrors.shou），这俩是大型商业公司支持的，而且质量确实很不错：镜像齐全，下载快（大公司的带宽嘛），但是就这它们也知道自己是商业公司，可能收到商业因素一干扰就会放弃，所以它们也就并没有去申请进入官方主源。
